### ISSUE TITLE
[FEATURE REQUEST] More Ores

### ISSUE THREAD

**Issue by jelaw21** [sekelsta/ore_reeds#2]
Instead of trying to match all the possible ores from all the mods, is it possible to add a config so that we can add our own ores to grow?

**Comment by sekelsta** [comment]
It might be a bit tricky, but I think I can do it. I won't have time for at least a month due to real life stuff, but after that I'll see what I can do.

**Comment by sekelsta** [comment]
Closing all feature request issues.
